# playbook_import_certs.yml
- name: Importaci칩n de Certificados en Brokers
  hosts: kafka-brokers
  become: yes
  tasks:
    - name: A침adir certificado CA al truststore
      command: >
        keytool -keystore /opt/kafka/ssl/kafka.server.truststore.jks -alias CARoot
        -import -file /opt/kafka/ssl/CA-files/ca-cert -storepass "{{ keystore_password }}"
        -keypass "{{ keystore_password }}" -noprompt
        
    - name: A침adir certificado CA al keystore
      command: >
        keytool -keystore /opt/kafka/ssl/kafka.server.keystore.jks -alias CARoot
        -import -file /opt/kafka/ssl/CA-files/ca-cert -storepass "{{ keystore_password }}"
        -keypass "{{ keystore_password }}" -noprompt
        
    - name: A침adir certificado firmado al keystore
      command: >
        keytool -keystore /opt/kafka/ssl/kafka.server.keystore.jks -import -file /opt/kafka/ssl/signed-cert
        -storepass "{{ keystore_password }}" -keypass "{{ keystore_password }}" -noprompt
