---
- name: Transferencia de Certificados
  hosts: ca-servers
  become: no
  vars:
    kafka_broker_ips: "{{ groups['kafka-brokers'] }}"
  tasks:
    - name: Transfer signed-cert from CA to Kafka broker
      synchronize:
        src: /opt/kafka/ssl/{{ item }}-signed-cert
        dest: /opt/kafka/ssl/signed-cert
        mode: pull
      delegate_to: "{{ item }}"
      with_items: "{{ kafka_broker_ips }}"

    - name: Transfer ca-cert from CA to Kafka broker
      synchronize:
        src: /opt/kafka/ssl/CA-files/ca-cert
        dest: /opt/kafka/ssl/CA-files/ca-cert
        mode: pull
      delegate_to: "{{ item }}"
      with_items: "{{ kafka_broker_ips }}"