# playbook_keystore_csr.yml
- name: Generación de Keystore y CSR
  hosts: kafka-brokers
  become: yes
  tasks:
    - name: Crear directorio para SSL
      file:
        path: /opt/kafka/ssl
        state: directory
        mode: '0755'

    - name: Ajustar propiedad del directorio SSL
      command: chown -R kafka:kafka /opt/kafka/ssl

    - name: Ajustar permisos del directorio SSL
      command: chmod -R 755 /opt/kafka/ssl
        
    - name: Generar keystore
      command: >
        keytool -genkey -keystore /opt/kafka/ssl/kafka.server.keystore.jks
        -keyalg RSA -validity 3652 -storepass "{{ keystore_password }}"
        -keypass "{{ keystore_password }}" -dname "CN={{ common_name }}"
        -storetype pkcs12
      args:
        creates: /opt/kafka/ssl/kafka.server.keystore.jks
        
    - name: Generar CSR
      command: >
        keytool -keystore /opt/kafka/ssl/kafka.server.keystore.jks -certreq
        -file /opt/kafka/ssl/{{ cert_sign_request_file_name }} -storepass "{{ keystore_password }}"
        -keypass "{{ keystore_password }}"
      args:
        creates: /opt/kafka/ssl/{{ cert_sign_request_file_name }}

- hosts: kafka-brokers
  tasks:
    - name: Transfer file from ServerA to ServerB
      synchronize:
        src: /opt/kafka/ssl/{{ cert_sign_request_file_name }}
        dest: /opt/kafka/ssl/sign-request/{{ inventory_hostname }}-{{ cert_sign_request_file_name }}
        mode: pull
      delegate_to: 192.168.1.143