# playbook_sign_csr.yml
- name: Firma de la CSR
  hosts: ca-servers
  become: yes
  tasks:
    - name: Firmar CSR
      command: >
        openssl x509 -req -CA /opt/kafka/ssl/CA-files/ca-cert -CAkey /opt/kafka/ssl/CA-files/ca-key
        -in /opt/kafka/ssl/sign-request/192.168.1.12-signing-request-file -out /opt/kafka/ssl/signed-cert
        -days 365 -CAcreateserial -passin pass:{{ keystore_password }}
      args:
        creates: /opt/kafka/ssl/signed-cert
