- name: Install Java
  hosts: zookeeper-nodes
  become: yes
  vars_files:
    - java-vars.yaml
  tasks:
    - name: Install Java OpenJDK 17
      dnf:
        name: java-17-openjdk
        state: present

    - name: Set JAVA_HOME in /etc/environment
      lineinfile:
        path: /etc/environment
        line: "JAVA_HOME={{ jdk_path }}"
        create: yes

    - name: Add Java to PATH in /etc/environment
      lineinfile:
        path: /etc/environment
        line: "PATH=$PATH:{{ jdk_path }}/bin"
        create: yes
    
    - name: Refresh environment variables
      shell: "source /etc/environment"
      args:
        executable: /bin/bash