---
- name: Crear el archivo de servicio para Zookeeper
  template:
    src: zookeeper.service.j2
    dest: "/etc/systemd/system/zookeeper.service"

- name: Crear el archivo de servicio para Kafka
  template:
    src: kafka.service.j2
    dest: "/etc/systemd/system/kafka.service"

- name: Recargar los archivos de servicio de systemd
  command: systemctl daemon-reload

- name: Iniciar y habilitar Zookeeper
  systemd:
    name: zookeeper
    state: started
    enabled: yes

- name: Iniciar y habilitar Kafka
  systemd:
    name: kafka
    state: started
    enabled: yes
