---
- name: Preparar y Configurar Kafka y Zookeeper
  hosts: kafka-brokers
  become: true
  vars:
    kafka_version: "3.7.0"
    kafka_bin_dir: "/opt/kafka/kafka_2.13-{{ kafka_version }}/bin"
    kafka_download_url: "https://downloads.apache.org/kafka/{{ kafka_version }}/kafka_2.13-{{ kafka_version }}.tgz"
    kafka_data_dir: "/kafka-logs"
    zookeeper_data_dir: "/zookeeper"
    kafka_conf_dir: "/opt/kafka/kafka-config"
    zookeeper_conf_file: "{{ kafka_conf_dir }}/zookeeper.properties"
    kafka_conf_file: "{{ kafka_conf_dir }}/kafka.properties"
    zookeeper_servers:
      - 192.168.1.143:2888:3888
      - 192.168.1.144:2888:3888
    kafka_servers:
      - "192.168.1.143:9092"
      - "192.168.1.144:9092"
    keystore_password: "kaf123"
    truststore_password: "kaf123"
    kafka_user: "kafka"
    kafka_group: "kafka"

  tasks:
    - name: Descargar y descomprimir Kafka
      get_url:
        url: "{{ kafka_download_url }}"
        dest: "/tmp/kafka.tgz"

    - name: Descomprimir Kafka
      unarchive:
        src: "/tmp/kafka.tgz"
        dest: "/opt/kafka"
        remote_src: yes

    - name: Añadir Kafka al PATH del usuario
      lineinfile:
        path: "/home/{{ kafka_user }}/.bashrc"
        line: 'PATH="$PATH:{{ kafka_bin_dir }}"'
        create: yes

    - name: Crear directorio de datos para Zookeeper
      file:
        path: "{{ zookeeper_data_dir }}"
        state: directory
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"

    - name: Crear archivo myid para Zookeeper
      copy:
        content: "{{ broker_id }}"
        dest: "{{ zookeeper_data_dir }}/myid"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"

    - name: Crear directorio de configuración de Kafka
      file:
        path: "{{ kafka_conf_dir }}"
        state: directory
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"

    - name: Configurar Zookeeper
      template:
        src: zookeeper.properties.j2
        dest: "{{ zookeeper_conf_file }}"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"

    - name: Configurar Kafka
      template:
        src: kafka.properties.j2
        dest: "{{ kafka_conf_file }}"
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"

    - name: Verificar y configurar permisos y propietarios de Kafka y Zookeeper
      file:
        path: "{{ item.path }}"
        state: directory
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0755'
      with_items:
        - { path: "/opt/kafka" }
        - { path: "{{ kafka_data_dir }}" }
        - { path: "{{ zookeeper_data_dir }}" }

    - name: Asegurarse de que los archivos de configuración tienen los permisos correctos
      file:
        path: "{{ item.path }}"
        state: file
        owner: "{{ kafka_user }}"
        group: "{{ kafka_group }}"
        mode: '0644'
      with_items:
        - { path: "{{ kafka_conf_file }}" }
        - { path: "{{ zookeeper_conf_file }}" }

    - name: Crear el archivo de servicio para Zookeeper
      template:
        src: zookeeper.service.j2
        dest: "/etc/systemd/system/zookeeper.service"

    - name: Crear el archivo de servicio para Kafka
      template:
        src: kafka.service.j2
        dest: "/etc/systemd/system/kafka.service"

    - name: Recargar los archivos de servicio de systemd
      command: systemctl daemon-reload

    - name: Iniciar y habilitar Zookeeper
      systemd:
        name: zookeeper
        state: started
        enabled: yes

    - name: Iniciar y habilitar Kafka
      systemd:
        name: kafka
        state: started
        enabled: yes

